language: python

notifications:
  email: false

env:
  global:
    - RURE_DIR=/opt/regex/regex-capi
      REGEX_TAG=0.1.80
matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/davidblewett/manylinux_rure
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/davidblewett/manylinux_rure
           PRE_CMD=linux32

install:
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
  - ls wheelhouse/
