cache:
  directories:
    - /root/.cache/pip
    - /root/.cargo

install:
  - docker pull $DOCKER_IMAGE

language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/davidblewett/manylinux_rure
           REGEX_TAG=0.1.80
           RURE_DIR=/opt/regex/regex-capi
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/davidblewett/manylinux_rure
           PRE_CMD=linux32
           REGEX_TAG=0.1.80
           RURE_DIR=/opt/regex/regex-capi

notifications:
  email: false

script:
  - docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
  - ls /io/wheelhouse/
